import { ClerkProvider } from '@clerk/nextjs'

import Header from "./components/header/header";
import Footer from "./components/footer/footer";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Header />
              {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
